### ISSUE TITLE
Todo list for 2018_W14_7_1438 convo between Stefan & M

### ISSUE THREAD

**Issue by mpacer** [scipy-conference/procbuild#31]
- [x] Verify that #29  is good to go
- [x] Talk through how to create sockets that respond to multiple channels and do appropriate things.
    - sockets are organised around channels, you can have sockets recv messages and then switch functionality on their target value/channel.
    - this should be useful for adding back the queue_size logic
- [x] Talk through how to setup basic travis stuff.
    - [x] Talk through how to autopush to dockerhub from travis
    - [x] Talk through how to autopush a Docker file to the heroku registry from within travis
- [x] Set up basic server test (so as to have something to test on travis to make sure it works correctly)

Stéfan added:

- [ ] What are we doing to keep the server alive?
- [ ] Can we preserve state across deployments? (One option is to  issue a build all by default with each new update.)

**Comment by mpacer** [comment]
@stefanv Here is a list of the things I had wanted to talk through today.

**Comment by mpacer** [comment]
@stefanv I don't think we have a good solution for keeping the server alive or preserving status
